; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EAPowerTools"
#define MyAppVersion "1.0"
#define MyAppPublisher "Redfish Labs"
#define MyAppURL "http://www.example.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E2176E4A-117E-4CCC-83CF-96EFA29AEC1C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=EAPowerTools
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\Jeff\Documents\Visual Studio 2015\Projects\EAPowerTools\EAPowerTools\bin\Debug\EAPowerTools.dll"; DestDir: "{app}"; StrongAssemblyName: "EAPowerTools, Version=1.0.0.0, PublicKeyToken=2f0bba969d577a7d, Culture=neutral, ProcessorArchitecture=MSIL"; Flags: gacinstall sharedfile
Source: "C:\Users\Jeff\Documents\Visual Studio 2015\Projects\EAPowerTools\EAPowerTools\bin\Debug\EAPowerTools.pdb"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKCU; Subkey: "Software\Sparx Systems\EAAddins\EAPowerTools"; ValueType: string; ValueData: "EAPowerTools.Main"; Flags: uninsdeletekey

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

